### ISSUE TITLE
Readme example not working

### ISSUE THREAD

**Issue by Juuhz** [ION606/linkedin-api#1]
I wanted an alternative to LinkedIn's Voyager API in JavaScript. I was excited about this package, but when I tried to run the example from the readme, nothing was displayed in my terminal; it simply didn't work. :confuso:

Do you know what could be the issue?

```
import linkedInAPIClass from "linkedin-api-js";

const main = async () => {
  const LAPI = new linkedInAPIClass();
  await LAPI.login("***", "***");

  // GET a company
  const comp = await LAPI.searchCompanies("Linux");

  // GET one employee
  const emp = await comp[0].getEmployees("Torvalds", 1);

  console.log("emp", emp);
};

main();

```

**Comment by ION606** [comment]
oh sorry my bad! I'll debug this and try to push a fix today, or update you if I can't qwq

**Comment by ION606** [comment]
@Juuhz I (think) I pushed a fix ^~^
https://github.com/ION606/linkedin-api/commit/b20519cbd5dac60ac7d7cc1c9e471f4c7ce69927

**Comment by Juuhz** [comment]
Error :/ 

```
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "python: can't open file 'my-project-path\\undefined\\auth.py': [Errno 2] No such file or directory
".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v18.18.0
```

Node.js v18.18.0
windows 11

**Comment by ION606** [comment]
huh. Very weird. Are you using 'require' or 'import'?

**Comment by Juuhz** [comment]
> huh. Very weird. Are you using 'require' or 'import'?

Import.

It seems that the path to `auth.py` cannot be found. When trying to provide the full path, undefined is returned.:

```python: can't open file 'my-project-path\\undefined\\auth.py'```

**Comment by Juuhz** [comment]
In the `API.js` file, just change the ``python ${import.meta.dirname}/auth.py ${username} ${password}`` part to `python classes/auth.py ${username} ${password}` on line 137 and it works. 

However, returning to login is a CHALLENGE, do you know how to solve it?

**Comment by ION606** [comment]
I'm so sorry! I pushed another fix. I can't seem to reproduce this on my system (I don't know why) but it should be good now ^~^

**Comment by ION606** [comment]
> In the `API.js` file, just change the ``python ${import.meta.dirname}/auth.py ${username} ${password}`` part to `python classes/auth.py ${username} ${password}` on line 137 and it works. 
> 
> 
> 
> However, returning to login is a CHALLENGE, do you know how to solve it?

as for the CHALLENGE issue, that is something I can't solve, it has to do with the linkedIn API and how they handle bot detection. The only way I've found around this is to:
1. log in through the browser
2. copy the cookie from a request
3. paste it into the cookie.txt file
4. re-run the program

this bypasses the captcha check hmhm

**Comment by Juuhz** [comment]
Great, I'll test it. Thanks for the tip.

Do you know what the safe rate limit is for executing multiple requests without being blocked?

**Comment by Juuhz** [comment]
> 2. copy the cookie from a request

Any cookie from any voyager api request? Or any specific cookie saved in the browser memory?

**Comment by ION606** [comment]
ummmmm for the rate limit I added in an evade function for that. As for the cookie, any request that's user-triggered will do it, like searching or clicking on stuff

**Comment by Juuhz** [comment]
Work for me!!! Tks for help. 

![image](https://github.com/user-attachments/assets/1f70f3fb-a1ce-4b6d-9117-7a5d83ccc6fa)

---

**Suggestion**: It would be great to have a method to search for all company information by urn or id name

Congratulations on the work!

**Comment by ION606** [comment]
unfortunately, I work 4 jobs lel, sho I don't hab much time but wdym  "search for all company information by urn or id name". Like something other than the methods in the "Company" class? Also thankies ^~^

**Comment by ION606** [comment]
am closing the issue but if you have a feature request or anything I'd love to help :3
